steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'react-client'
    args: ['install']
  
  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'react-client'
    args: ['test']

  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'react-client'
    args: ['run', 'build']
options:
  logging: CLOUD_LOGGING_ONLY
