steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'react-client'
    args: ['install']
  
  # Run tests
  #- name: 'gcr.io/cloud-builders/npm'
  #  dir: 'react-client'
  #  args: ['test']

  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'react-client'
    args: ['run', 'build']
    
    # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'react-client'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/frontendimage/frontendimage', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'react-client'
    args: ['push','us-central1-docker.pkg.dev/${PROJECT_ID}/frontendimage/frontendimage']
    
  - name: 'maven:3.3-jdk-8'
    dir: 'spring-boot-server'
    entrypoint: mvn
    args: ['test']
options:
  logging: CLOUD_LOGGING_ONLY
